require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/business_ideas", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # BusinessIdea. As you add validations to BusinessIdea, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      BusinessIdea.create! valid_attributes
      get business_ideas_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      business_idea = BusinessIdea.create! valid_attributes
      get business_idea_url(business_idea)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_business_idea_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      business_idea = BusinessIdea.create! valid_attributes
      get edit_business_idea_url(business_idea)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new BusinessIdea" do
        expect {
          post business_ideas_url, params: { business_idea: valid_attributes }
        }.to change(BusinessIdea, :count).by(1)
      end

      it "redirects to the created business_idea" do
        post business_ideas_url, params: { business_idea: valid_attributes }
        expect(response).to redirect_to(business_idea_url(BusinessIdea.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new BusinessIdea" do
        expect {
          post business_ideas_url, params: { business_idea: invalid_attributes }
        }.to change(BusinessIdea, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post business_ideas_url, params: { business_idea: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested business_idea" do
        business_idea = BusinessIdea.create! valid_attributes
        patch business_idea_url(business_idea), params: { business_idea: new_attributes }
        business_idea.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the business_idea" do
        business_idea = BusinessIdea.create! valid_attributes
        patch business_idea_url(business_idea), params: { business_idea: new_attributes }
        business_idea.reload
        expect(response).to redirect_to(business_idea_url(business_idea))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        business_idea = BusinessIdea.create! valid_attributes
        patch business_idea_url(business_idea), params: { business_idea: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested business_idea" do
      business_idea = BusinessIdea.create! valid_attributes
      expect {
        delete business_idea_url(business_idea)
      }.to change(BusinessIdea, :count).by(-1)
    end

    it "redirects to the business_ideas list" do
      business_idea = BusinessIdea.create! valid_attributes
      delete business_idea_url(business_idea)
      expect(response).to redirect_to(business_ideas_url)
    end
  end
end
