require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/entrepreneurial_skills_user_responses", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # EntrepreneurialSkillsUserResponse. As you add validations to EntrepreneurialSkillsUserResponse, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      EntrepreneurialSkillsUserResponse.create! valid_attributes
      get entrepreneurial_skills_user_responses_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      entrepreneurial_skills_user_response = EntrepreneurialSkillsUserResponse.create! valid_attributes
      get entrepreneurial_skills_user_response_url(entrepreneurial_skills_user_response)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_entrepreneurial_skills_user_response_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      entrepreneurial_skills_user_response = EntrepreneurialSkillsUserResponse.create! valid_attributes
      get edit_entrepreneurial_skills_user_response_url(entrepreneurial_skills_user_response)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new EntrepreneurialSkillsUserResponse" do
        expect {
          post entrepreneurial_skills_user_responses_url, params: { entrepreneurial_skills_user_response: valid_attributes }
        }.to change(EntrepreneurialSkillsUserResponse, :count).by(1)
      end

      it "redirects to the created entrepreneurial_skills_user_response" do
        post entrepreneurial_skills_user_responses_url, params: { entrepreneurial_skills_user_response: valid_attributes }
        expect(response).to redirect_to(entrepreneurial_skills_user_response_url(EntrepreneurialSkillsUserResponse.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new EntrepreneurialSkillsUserResponse" do
        expect {
          post entrepreneurial_skills_user_responses_url, params: { entrepreneurial_skills_user_response: invalid_attributes }
        }.to change(EntrepreneurialSkillsUserResponse, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post entrepreneurial_skills_user_responses_url, params: { entrepreneurial_skills_user_response: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested entrepreneurial_skills_user_response" do
        entrepreneurial_skills_user_response = EntrepreneurialSkillsUserResponse.create! valid_attributes
        patch entrepreneurial_skills_user_response_url(entrepreneurial_skills_user_response), params: { entrepreneurial_skills_user_response: new_attributes }
        entrepreneurial_skills_user_response.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the entrepreneurial_skills_user_response" do
        entrepreneurial_skills_user_response = EntrepreneurialSkillsUserResponse.create! valid_attributes
        patch entrepreneurial_skills_user_response_url(entrepreneurial_skills_user_response), params: { entrepreneurial_skills_user_response: new_attributes }
        entrepreneurial_skills_user_response.reload
        expect(response).to redirect_to(entrepreneurial_skills_user_response_url(entrepreneurial_skills_user_response))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        entrepreneurial_skills_user_response = EntrepreneurialSkillsUserResponse.create! valid_attributes
        patch entrepreneurial_skills_user_response_url(entrepreneurial_skills_user_response), params: { entrepreneurial_skills_user_response: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested entrepreneurial_skills_user_response" do
      entrepreneurial_skills_user_response = EntrepreneurialSkillsUserResponse.create! valid_attributes
      expect {
        delete entrepreneurial_skills_user_response_url(entrepreneurial_skills_user_response)
      }.to change(EntrepreneurialSkillsUserResponse, :count).by(-1)
    end

    it "redirects to the entrepreneurial_skills_user_responses list" do
      entrepreneurial_skills_user_response = EntrepreneurialSkillsUserResponse.create! valid_attributes
      delete entrepreneurial_skills_user_response_url(entrepreneurial_skills_user_response)
      expect(response).to redirect_to(entrepreneurial_skills_user_responses_url)
    end
  end
end
