require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/funding_plans", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # FundingPlan. As you add validations to FundingPlan, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      FundingPlan.create! valid_attributes
      get funding_plans_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      funding_plan = FundingPlan.create! valid_attributes
      get funding_plan_url(funding_plan)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_funding_plan_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      funding_plan = FundingPlan.create! valid_attributes
      get edit_funding_plan_url(funding_plan)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new FundingPlan" do
        expect {
          post funding_plans_url, params: { funding_plan: valid_attributes }
        }.to change(FundingPlan, :count).by(1)
      end

      it "redirects to the created funding_plan" do
        post funding_plans_url, params: { funding_plan: valid_attributes }
        expect(response).to redirect_to(funding_plan_url(FundingPlan.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new FundingPlan" do
        expect {
          post funding_plans_url, params: { funding_plan: invalid_attributes }
        }.to change(FundingPlan, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post funding_plans_url, params: { funding_plan: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested funding_plan" do
        funding_plan = FundingPlan.create! valid_attributes
        patch funding_plan_url(funding_plan), params: { funding_plan: new_attributes }
        funding_plan.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the funding_plan" do
        funding_plan = FundingPlan.create! valid_attributes
        patch funding_plan_url(funding_plan), params: { funding_plan: new_attributes }
        funding_plan.reload
        expect(response).to redirect_to(funding_plan_url(funding_plan))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        funding_plan = FundingPlan.create! valid_attributes
        patch funding_plan_url(funding_plan), params: { funding_plan: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested funding_plan" do
      funding_plan = FundingPlan.create! valid_attributes
      expect {
        delete funding_plan_url(funding_plan)
      }.to change(FundingPlan, :count).by(-1)
    end

    it "redirects to the funding_plans list" do
      funding_plan = FundingPlan.create! valid_attributes
      delete funding_plan_url(funding_plan)
      expect(response).to redirect_to(funding_plans_url)
    end
  end
end
