require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/swot_analyses", type: :request do
  before { skip("Waiting for a decision about the relationship between the models") }
  # This should return the minimal set of attributes required to create a valid
  # SwotAnalysis. As you add validations to SwotAnalysis, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      SwotAnalysis.create! valid_attributes
      get swot_analyses_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      swot_analysis = SwotAnalysis.create! valid_attributes
      get swot_analysis_url(swot_analysis)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_swot_analysis_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      swot_analysis = SwotAnalysis.create! valid_attributes
      get edit_swot_analysis_url(swot_analysis)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new SwotAnalysis" do
        expect {
          post swot_analyses_url, params: { swot_analysis: valid_attributes }
        }.to change(SwotAnalysis, :count).by(1)
      end

      it "redirects to the created swot_analysis" do
        post swot_analyses_url, params: { swot_analysis: valid_attributes }
        expect(response).to redirect_to(swot_analysis_url(SwotAnalysis.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new SwotAnalysis" do
        expect {
          post swot_analyses_url, params: { swot_analysis: invalid_attributes }
        }.to change(SwotAnalysis, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post swot_analyses_url, params: { swot_analysis: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested swot_analysis" do
        swot_analysis = SwotAnalysis.create! valid_attributes
        patch swot_analysis_url(swot_analysis), params: { swot_analysis: new_attributes }
        swot_analysis.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the swot_analysis" do
        swot_analysis = SwotAnalysis.create! valid_attributes
        patch swot_analysis_url(swot_analysis), params: { swot_analysis: new_attributes }
        swot_analysis.reload
        expect(response).to redirect_to(swot_analysis_url(swot_analysis))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        swot_analysis = SwotAnalysis.create! valid_attributes
        patch swot_analysis_url(swot_analysis), params: { swot_analysis: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested swot_analysis" do
      swot_analysis = SwotAnalysis.create! valid_attributes
      expect {
        delete swot_analysis_url(swot_analysis)
      }.to change(SwotAnalysis, :count).by(-1)
    end

    it "redirects to the swot_analyses list" do
      swot_analysis = SwotAnalysis.create! valid_attributes
      delete swot_analysis_url(swot_analysis)
      expect(response).to redirect_to(swot_analyses_url)
    end
  end
end
