# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem "sqlite3"
#
default: &default
  adapter: <%= ENV.fetch("DB_ADAPTER") { "sqlite3" } %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  # database: storage/development.sqlite3
  adapter: postgresql
  encoding: unicode
  database: myapp_development
  pool: 5
  username: <%= ENV["PG_USERNAME"] || "maciej" %>
  password: <%= ENV["PG_PASSWORD"] || "maciej" %>
  host: <%= ENV["PG_HOST"] || "localhost" %>

test:
  adapter: postgresql
  encoding: unicode
  database: myapp_test
  pool: 5
  username: <%= ENV["PG_USERNAME"] || "maciej" %>
  password: <%= ENV["PG_PASSWORD"] || "maciej" %>
  host: <%= ENV["PG_HOST"] || "localhost" %>

production:
  <<: *default
  adapter: postgresql
  encoding: unicode
  database: business_production
  username: business
  password: <%= ENV["BUSINESS_DATABASE_PASSWORD"] %>
  pool: 5
